### ISSUE TITLE
Alteração na comparacao

### ISSUE THREAD

**Issue by developerspro** [Felps-N/AtvfinalDES#1]
https://github.com/Felps-N/AtvfinalDES/blob/841d3772e7b45bf1be4cd5189ff3715d1ce97d65/Atendimento%20Hospitalar/Program.cs#L20

use ToUpper().Equals()

**Comment by Felps-N** [comment]
https://github.com/Felps-N/AtvfinalDES/blob/841d3772e7b45bf1be4cd5189ff3715d1ce97d65/Atendimento%20Hospitalar/Menu.cs#L25

alterado para return escolha.ToUpper();
